=== PASAUCMerced/NVC/Benchmarks/Recomputation/specOMP_install/Docs/flags/cpuflags2.dtd
<!--
   SPEC CPU Flag Description File 1.2 DTD

   This DTD describes the XML used to describe compilation flags for
   benchmark suites using the SPEC CPU benchmark harness.

   For further information, see
       http://www.spec.org/cpu2006/Docs/flag-description.html

   Copyright 2005-2011 Standard Performance Evaluation Corporation
   All Rights Reserved. 

   This DTD module is identified by the PUBLIC and SYSTEM identifiers:

   PUBLIC "-//SPEC//DTD SPEC CPU Flags Description 1.2//EN"
   SYSTEM "http://www.spec.org/dtd/cpuflags2.dtd"

   ...is what I'd like to say, but we don't have a SPEC entry in any of
   the catalogs, so we'll just have to make do with SYSTEM for now.

   $Id: cpuflags2.dtd 6491 2011-05-06 18:54:19Z cloyce $

-->

  <!-- The list of allowable classes for flags and headers           -->
  <!-- This list also lives in CPUFlagParser.pm and flags.pl; if you -->
  <!-- change it, do not forget to update those files.               -->
<!ENTITY % Classes "mandatory | forbidden |
                    portability | optimization |
                    compiler | other |
                    unknown" >

  <!-- The list of allowable ways to say "yes" and "no" -->
<!ENTITY % YesNo "(0 | 1 | no | yes | off | on |
                           No | Yes | Off | On |
                           NO | YES | OFF | ON)" >

<!-- flagsdescription is the root element -->
<!ELEMENT flagsdescription (filename,title,style?,submit_command?,sw_environment?,((os_tuning?,virtual_machine?,firmware?,parts?) | (fdo_settings?,header*,flag*)),dumpit?)>

<!-- The filename element allows the flag description writer to SUGGEST
     a filename to use when storing a flag description that has been
     transmitted via a non-name-preserving channel (encoded into a raw file,
     flags file upload to SPEC, etc).
-->
<!ELEMENT filename (#PCDATA)>

<!-- The title element contains the text that will be used in the
     <title>...</title> section of the HTML flag dump.
-->
<!ELEMENT title (#PCDATA)>

<!-- style is an optional element which may contain CSS code to be
     inserted at the bottom of the local <style>..</style> section.
     This can be used to define new classes (which you can use in your
     header section and flag descriptions), or to override the supplied
     default styles.  For ease of use, the CSS code should probably be
     contained within a CDATA section:
     !<[CDATA[
     ...CSS goes here...
     ]]>
-->
<!ELEMENT style (#PCDATA)>

<!-- header is an optional element which may contain HTML code to be
     inserted at the top of the HTML flag dump and (default class only)
     at the top of the per-result flag report.  For ease of use, the HTML
     markup should be contained within a CDATA section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT header (#PCDATA)>
<!ATTLIST header
      class (%Classes;) #IMPLIED
>

<!-- submit_command is an optional element which describes commands, options,
     and scripts used with submit.  If present, it should contain valid HTML
     code, which will be inserted at the bottom of the HTML flags dump and
     the per-result flags report.
     For ease of use, the HTML markup should be contained within a CDATA
     section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT submit_command (#PCDATA)>

<!-- sw_environment is an optional element which describes shell resources,
     environment variables, and other software options or installation
     settings.
     If present, it should contain valid HTML code, which will be inserted
     at the bottom of the HTML flags dump and the per-result flags report.
     For ease of use, the HTML markup should be contained within a CDATA
     section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT sw_environment (#PCDATA)>

<!-- fdo_settings is an optional element which describes non-compiler
     commands used to process benchmark binaries during FDO builds.
     If present, it should contain valid HTML code, which will be inserted
     at the bottom of the HTML flags dump and the per-result flags report.
     For ease of use, the HTML markup should be contained within a CDATA
     section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT fdo_settings (#PCDATA)>

<!-- os_tuning is an optional element which describes operating system
     install options, boot settings, and other operating system configuration
     options.
     If present, it should contain valid HTML code, which will be inserted
     at the bottom of the HTML flags dump and the per-result flags report.
     For ease of use, the HTML markup should be contained within a CDATA
     section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT os_tuning (#PCDATA)>

<!-- virtual_machine is an optional element which describes settings
     pertaining to hypervisors, domains, partitioning, or any other
     virtualization technology.
     If present, it should contain valid HTML code, which will be inserted
     at the bottom of the HTML flags dump and the per-result flags report.
     For ease of use, the HTML markup should be contained within a CDATA
     section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT virtual_machine (#PCDATA)>

<!-- firmware is an optional element which describes firmware, BIOS,
     or microcode settings.
     If present, it should contain valid HTML code, which will be inserted
     at the bottom of the HTML flags dump and the per-result flags report.
     For ease of use, the HTML markup should be contained within a CDATA
     section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT firmware (#PCDATA)>

<!-- parts is an optional element which describes hardware and software
     parts and options needed to complete the system.
     If present, it should contain valid HTML code, which will be inserted
     at the bottom of the HTML flags dump and the per-result flags report.
     For ease of use, the HTML markup should be contained within a CDATA
     section:
     !<[CDATA[
     ...HTML goes here...
     ]]>
-->
<!ELEMENT parts (#PCDATA)>

<!-- The flag element describes one single flag.  Documentation for its
     attributes and their values is long and has already been written.  See
     the reference at the top of the page.
-->
<!ELEMENT flag (#PCDATA | include | ex_replacement | display | example)*>
<!ATTLIST flag
      name ID #REQUIRED
      class (%Classes;) #REQUIRED
      regexp CDATA #IMPLIED
      compilers CDATA #IMPLIED
      parallel %YesNo; "0"
>

<!-- example is used to specify example flag text when the name is not
     appropriate for display.
-->
<!ELEMENT example (#PCDATA)>

<!-- ex_replacement is used to specify one or more values for replacing
     $1, $2, etc in description text when that text is to be output and
     no replacement text from a match is available (as when formatting the
     whole list of flags as HTML).
-->
<!ELEMENT ex_replacement (#PCDATA)>

<!-- The include element is used to note that a flag either implies the
     presence of another flag (the 'flag' attribute) or should insert
     some text back into the variable in which it matched (the 'text'
     attribute.  The 'flagtext' attribute is used ONLY in conjunction with
     the 'flag' attribute to specify the text of a flag that should be used
     for display.
-->
<!ELEMENT include EMPTY>
<!ATTLIST include
      flag IDREF #IMPLIED
      flagtext CDATA #IMPLIED
      text CDATA #IMPLIED
>

<!-- The display element is used to specify whether or not a particular
     flag description should be displayed.  A flag must be marked for
     display (the default) unless it contains ONLY text includes.  The
     DTD does not enforce this, but runspec and friends will.
-->
<!ELEMENT display EMPTY>
<!ATTLIST display
      enable %YesNo; "1"
>

<!-- dumpit is an undocumented element.  It might cause something to happen. -->
<!ELEMENT dumpit (#PCDATA)>

=== PASAUCMerced/NVC/Benchmarks/Recomputation/specOMP_install/benchspec/OMP2012/359.botsspar/Spec/flags.xml
<?xml version="1.0"?>
<!DOCTYPE flagsdescription SYSTEM
       "http://www.spec.org/dtd/cpuflags2.dtd">

<!-- This file defines portability flags that may be used when compiling
     359.botsspar.

  Copyright 2012 Standard Performance Evaluation Corporation

  $Revision: 366 $
  $Date: 2012-06-26 19:41:25 -0400 (Tue, 26 Jun 2012) $
-->
<flagsdescription>

<filename>359.botsspar.flags</filename>
<title>359.botsspar Approved Portability Flags</title>

<header>
<![CDATA[
<p>This is the complete set of approved portability flags for 359.botsspar.</p>
]]>
</header>

<flag name="currdir_inc" class="mandatory" regexp="-I\.(?:/omp-tasks/sparselu/sparselu_single|/common)?(?:\s+|$)">
<example>-I. -I./omp-tasks/sparselu/sparselu_single -I./common </example>
This flag is included automatically by Spec/object.pm.
</flag>

<flag name="DBOTS_APP_CHECK_USES_SEQ_RESULT" class="forbidden">
Used for comparing sequential to parallel results, do not set.
</flag>

<flag name="DBOTS_APP_DEF_ARG_BLOCK" class="forbidden">
Sets the default argument block, must not be changed for SPEC run.
</flag>

<flag name="DBOTS_APP_DEF_ARG_CUTOFF" class="forbidden">
Sets the default cutoff for for the first argument, must not be changed 
for SPEC run.
</flag>

<flag name="DBOTS_APP_DEF_ARG_CUTOFF_1" class="forbidden">
Sets the default cutoff for for the second argument, must not be changed
for SPEC run.
</flag>

<flag name="DBOTS_APP_DEF_ARG_CUTOFF_2" class="forbidden">
Sets the default cutoff for for the third argument, must not be changed 
for SPEC run.
</flag>

<flag name="DBOTS_APP_DEF_ARG_REPETITIONS" class="forbidden">
Defines argument repetition for BOTS if used, do not change for SPEC.
</flag>

<flag name="DBOTS_APP_DEF_ARG_SIZE" class="forbidden">
Sets the default value for for the first argument, must not be changed 
for SPEC run.
</flag>

<flag name="DBOTS_APP_DEF_ARG_SIZE_1" class="forbidden">
Sets the default value for for the second argument, must not be changed 
for SPEC run.
</flag>

<flag name="DBOTS_APP_DEF_ARG_SIZE_2" class="forbidden">
Sets the default value for for the third argument, must not be changed 
for SPEC run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_BLOCK" class="forbidden">
Describes argument block to BOTS if needed, do not set for SPEC run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_CUTOFF" class="forbidden">
Describes first argument cutoff to BOTS if needed, do not set for SPEC 
run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_CUTOFF_1" class="forbidden">
Describes second argument cutoff to BOTS if needed, do not set for SPEC 
run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_CUTOFF_2" class="forbidden">
Describes third argument cutoff to BOTS if needed, do not set for SPEC 
run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_FILE" class="forbidden">
Describes the argument file to BOTS if needed, do not set for SPEC run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_REPETITIONS" class="forbidden">
Describes argument repetition to BOTS if needed, do not set for SPEC 
run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_SIZE" class="forbidden">
Describes the value of the first argument, must not be changed for a 
SPEC run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_SIZE_1" class="forbidden">
Describes the value of the second argument, must not be changed for a 
SPEC run.
</flag>

<flag name="DBOTS_APP_DESC_ARG_SIZE_2" class="forbidden">
Describes the value of the third argument, must not be changed for a 
SPEC run.
</flag>

<flag name="DBOTS_APP_FINI" class="forbidden">
Sets the end message, cannot be changed for SPEC run.
</flag>

<flag name="DBOTS_APP_INIT" class="forbidden">
Sets the value init types, cannot be changed for SPEC run.
</flag>

<flag name="DBOTS_APP_NAME" class="forbidden">
Sets the name of what is being run, cannot be changed for SPEC run.
</flag>

<flag name="DBOTS_APP_PARAMETERS_DESC" class="forbidden">
Describes elements of the BOTS test, cannot be changed for SPEC run.
</flag>

<flag name="DBOTS_APP_PARAMETERS_LIST" class="forbidden">
Lists the paramaters of the run, cannot be changed for SPEC run.
</flag>

<flag name="DBOTS_APP_SELF_TIMING" class="forbidden">
Tells BOTS to do self timing, do not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_ARG_BLOCK" class="forbidden">
Tells BOTS how arguments are supplied, do not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_ARG_CUTOFF" class="forbidden">
Tells BOTS if first cutoff is to be used, do not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_ARG_CUTOFF_1" class="forbidden">
Tells BOTS if second cutoff is to be used, do not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_ARG_CUTOFF_2" class="forbidden">
Tells BOTS if third cutoff is to be used, do not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_ARG_FILE" class="forbidden">
Tells BOTS if argument file is used, do not change for SPEC.
</flag>

<flag name="DBOTS_APP_USES_ARG_REPETITIONS" class="forbidden">
Tells BOTS if argument repetition is used, do not change for SPEC.
</flag>

<flag name="DBOTS_APP_USES_ARG_SIZE" class="forbidden">
Tells BOTS that it is using arguments, must not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_ARG_SIZE_1" class="forbidden">
Tells BOTS that it is using arguments, must not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_ARG_SIZE_2" class="forbidden">
Tells BOTS that it is using arguments, must not change for SPEC run.
</flag>

<flag name="DBOTS_APP_USES_REPETITIONS" class="forbidden">
Tells BOTS repetition is to be used, do not change for SPEC run.
</flag>

<flag name="DBOTS_DEBUG" class="forbidden">
Used to allow BOTS debugging, not to be set for SPEC runs.
</flag>

<flag name="DBOTS_MODEL_DESC" class="forbidden">
This describes the model being run.  Not to be changes for a SPEC run.
</flag>

<flag name="DCC" class="forbidden">
Sets the value of the C compiler being used, not to be set for 
submittable benchmark run.
</flag>

<flag name="DCDATE" class="forbidden">
Lists the date of the compile, not to be set for submittable run.
</flag>

<flag name="DCFLAGS" class="forbidden">
Sets the values of the C compiler flags being used, not to be set for 
submittable benchmark run.
</flag>

<flag name="DCMESSAGE" class="forbidden">
Sets a message for a BOTS run, do not use for SPEC.
</flag>

<flag name="DFINAL_CUTOFF" class="forbidden">
Defines a final cutoff value, not to be used for SPEC run.
</flag>

<flag name="DFORCE_TIED_TASKS" class="forbidden">
This causes the benchmark to be run with tied tasks.  Not allowed for
SPEC runs.
</flag>

<flag name="DIF_CUTOFF" class="forbidden">
Defines if cutoff value, not to be changed for SPEC run.
</flag>

<flag name="DKERNEL_CALL" class="forbidden">
Sets the name of the kernel call, must not be changed for SPEC run.
</flag>

<flag name="DKERNEL_CHECK" class="forbidden">
Sets the name of the kernel results check call, must not be changed for 
SPEC run.
</flag>

<flag name="DKERNEL_FINI" class="forbidden">
Sets the name of the kernel end call, must not be changed for SPEC run.
</flag>

<flag name="DKERNEL_INIT" class="forbidden">
Sets the name of the kernel init call, must not be changed for SPEC run.
</flag>

<flag name="DKERNEL_SEQ_CALL" class="forbidden">
Sets the name of the sequential kernel call, must not be 
changed for SPEC run.
</flag>

<flag name="DKERNEL_SEQ_FINI" class="forbidden">
Sets the name of the kernel sequential end call, must not be changed 
for SPEC run.
</flag>

<flag name="DKERNEL_SEQ_INIT" class="forbidden">
Sets the name of the kernel sequential init call, must not be changed 
for SPEC run.
</flag>

<flag name="DLD" class="forbidden">
Sets the value of the loader being used, not to be set for 
submittable benchmark run.
</flag>

<flag name="DLDFLAGS" class="forbidden">
Sets the values of the load flags being used, not to be set for 
submittable benchmark run.
</flag>

<flag name="DMANUAL_CUTOFF" class="forbidden">
Defines manual cutoff value, not to be changed for SPEC run.
</flag>

<flag name="DSPARSELU_H" class="forbidden">
Include file fence, do not change for SPEC run.
</flag>

<flag name="D_BOTS_H_" class="forbidden">
Internal to BOTS, include file guard, do not use.
</flag>

<flag name="D_COMMON_H" class="forbidden">
Internal to BOTS include setting of define, not to be messed with for
SPEC run.
</flag>

<flag name="D_OPENMP" class="forbidden">
Generic definition of OPENMP define, SPEC runs will use SPEC_OMP.
</flag>

<flag name="D__linux" class="forbidden">
Assumes that things are being done on a linux box, which causes specific
output for linux, not to be set for benchmark on the compile line.
</flag>


</flagsdescription>

=== PASAUCMerced/NVC/Benchmarks/Recomputation/specOMP_install/benchspec/flags-mandatory.xml
<?xml version="1.0"?>
<!DOCTYPE flagsdescription
    SYSTEM "http://www.spec.org/dtd/cpuflags2.dtd"
>

<!-- This file defines flags in the 'mandatory' class; that is, flags which are
     automatically supplied by the tools for ALL benchmarks.
     Flags in this class are ignored when doing per-flag checks for a
     particular run (because they are always present), but _are_
     output in the full flag report.

  Copyright 2005-2011 Standard Performance Evaluation Corporation

  $Revision: 305 $
  $Date: 2012-03-29 13:14:46 -0400 (Thu, 29 Mar 2012) $
-->
<flagsdescription>

<!-- Normal flags files should suggest a name for themselves. -->
<filename>flags_mandatory</filename>

<title>SPEC OMP2012 Default Flags</title>

<header>
<![CDATA[
<h2>SPEC OMP2012 Default Flags</h2>

<p>These are the flags that are universally supplied by the tools harness.</p>
]]>
</header>

<flag name="DSPEC" class="mandatory">
The preprocessor macro SPEC is defined for all benchmarks compiled
by the OMP2012 tools harness.
</flag>

<flag name="USPEC" class="forbidden">
It is forbidden to undefine this mandatory flag.
</flag>

<flag name="DSPEC_OPENMP" class="mandatory">
The preprocessor macro SPEC_OPENMP is defined for all benchmarks compiled
by the OMP2012 tools harness.
</flag>

<flag name="DSPEC_OMP" class="mandatory">
The preprocessor macro SPEC_OMP is defined for all benchmarks compiled
by the OMP2012 tools harness.
</flag>

<flag name="USPEC_OPENMP" class="forbidden">
It is forbidden to undefine this mandatory flag.
</flag>

<flag name="USPEC_OMP" class="forbidden">
It is forbidden to undefine this mandatory flag.
</flag>

<flag name="DSPEC_MPI" class="forbidden">
It is forbidden to define this flag.
</flag>

<flag name="DNDEBUG" class="mandatory">
The preprocessor macro NDEBUG is defined for all benchmarks compiled
by the OMP2012 tools harness.  It is used to disable asserts() in codes
that use them.
</flag>

<flag name="UNDEBUG" class="forbidden">
It is forbidden to undefine this mandatory flag.
</flag>

<flag name="DSPEC_WINDOWS" class="mandatory">
The preprocessor macro SPEC_WINDOWS is defined for all benchmarks
compiled by the OMP2012 tools harness on Microsoft Windows systems.
</flag>

<flag name="DSPEC_OMP_WINDOWS" class="mandatory">
The preprocessor macro SPEC_OMP_WINDOWS is defined for all benchmarks
compiled by the OMP2012 tools harness on Microsoft Windows systems.
</flag>

<flag name="compile_opt" class="mandatory" regexp="(?:^|(?&lt;=\s))-c\b">
This is a part of the default setting for OBJOPT for all platforms.  It
causes an object file to be generated from source.
</flag>

<flag name="unix_output" class="mandatory" regexp="(?:^|(?&lt;=\s))-o [^\s\&quot;]+">
This option is used to specify the name of the output file on non-Windows platforms.
</flag>

<flag name="unix_mathlib" class="mandatory" regexp="(?:^|(?&lt;=\s))-lm\b">
This is the default setting for MATHLIBOPT on non-Windows platforms.
</flag>

<flag name="windows_compout" class="mandatory" regexp="(?:^|(?&lt;=\s))-Fo\S+\b">
This option is used to specify the name of the output object file on Windows platforms.
</flag>

<flag name="windows_ldout" class="mandatory" regexp="(?:^|(?&lt;=\s))-Fe\S+\b">
This option is used to specify the name of the output executable on Windows platforms.
</flag>

<flag name="DSPEC_ILP32" class="portability">
This option is used to indicate that the host system's integers, longs, and
pointers are 32-bits wide.  Not all benchmarks recognize this macro, but
the preferred practice for data model selection applies the flags to all
benchmarks; this flag description is a placeholder for those benchmarks that
do not recognize this macro.
</flag>

<flag name="DSPEC_P64" class="portability">
This option is used to indicate that the host system's integers and longs,
are 32-bits wide, and pointers are 64-bits wide.  Not all benchmarks
recognize this macro, but the preferred practice for data model selection
applies the flags to all benchmarks; this flag description is a placeholder
for those benchmarks that do not recognize this macro.
</flag>

<flag name="DSPEC_LP64" class="portability">
This option is used to indicate that the host system's integers are 32-bits
wide, and longs and pointers are 64-bits wide.  Not all benchmarks
recognize this macro, but the preferred practice for data model selection
applies the flags to all benchmarks; this flag description is a placeholder
for those benchmarks that do not recognize this macro.
</flag>

<flag name="DSPEC_ILP64" class="portability">
This option is used to indicate that the host system's integers, longs,
and pointers are 64-bits wide.  Not all benchmarks recognize this macro,
but the preferred practice for data model selection applies the flags to
all benchmarks; this flag description is a placeholder for those benchmarks
that do not recognize this macro.
</flag>


</flagsdescription>
